apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/emzm17/argocd-setup.git
    targetRevision: HEAD
    path: app1-config/config
  destination:
    server: https://kubernetes.default.svc
    namespace: app1-ns